# Usa a imagem oficial do MongoDB como base
FROM mongo:latest

# Define variáveis de ambiente úteis (pode ser genéricas)
ENV MONGO_INITDB_DATABASE=blog_posts

# Cria diretório para armazenar dados (opcional)
VOLUME ["/data/db"]

# Expõe a porta padrão do MongoDB
EXPOSE 27017

# Comando padrão ao iniciar o container
CMD ["mongod"]
