version: "3.8"

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: blog_posts
